on:
  pull_request:
  push:
    branches: main

jobs:
  create_pr_automerge:
    runs-on: ubuntu-latest
    name: Create pr and automerge to release brnaches
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Execute script
        uses: ./.github/actions/create_pr_automerge
