on:
  pull_request:
  push:
    branches: main

jobs:
  prautomerge:
    runs-on: ubuntu-latest
    name: Pr Auto Merge
    steps:
      - id: CheckoutRepository
        uses: actions/checkout@v3
      - run: |
          prUrl="$gh pr create --base main --head dev01 --title '[automated] pr release dev01' --body '[automated] pr release dev01'"
          echo 'PR_URL='$prUrl >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          gh pr merge "$PR_URL" --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
