on:
  pull_request:
  push:
    branches: main

jobs:
  prautomerge:
    runs-on: ubuntu-latest
    name: prautomerge
    steps:
      - id: CheckoutRepository
        uses: actions/checkout@v3
      - id: ExecuteScrit
        uses: ./.github/actions/prautomerge
